class StationInfo {
  final String id;
  final String name;
  final List<String> areaIds;
  const StationInfo({required this.id, required this.name, required this.areaIds});
}

class StationMap {
  static const List<StationInfo> stations = [
    StationInfo(id: '802', name: 'FM802', areaIds: ['JP25', 'JP26', 'JP27', 'JP28', 'JP29', 'JP30']),
    StationInfo(id: 'HBC', name: 'ＨＢＣラジオ', areaIds: ['JP1']),
    StationInfo(id: 'STV', name: 'ＳＴＶラジオ', areaIds: ['JP1']),
    StationInfo(id: 'AIR-G', name: "AIR-G'（FM北海道）", areaIds: ['JP1']),
    StationInfo(id: 'NORTHWAVE', name: 'FM NORTH WAVE', areaIds: ['JP1']),
    StationInfo(id: 'RAB', name: 'ＲＡＢ青森放送', areaIds: ['JP2']),
    StationInfo(id: 'AFB', name: 'エフエム青森', areaIds: ['JP2']),
    StationInfo(id: 'IBC', name: 'IBCラジオ', areaIds: ['JP3']),
    StationInfo(id: 'FMI', name: 'エフエム岩手', areaIds: ['JP3']),
    StationInfo(id: 'TBC', name: 'tbcラジオ', areaIds: ['JP4']),
    StationInfo(id: 'DATEFM', name: 'Date fm（エフエム仙台）', areaIds: ['JP4']),
    StationInfo(id: 'ABS', name: 'ABSラジオ', areaIds: ['JP5']),
    StationInfo(id: 'AFM', name: 'エフエム秋田', areaIds: ['JP5']),
    StationInfo(id: 'YBC', name: 'YBC山形放送', areaIds: ['JP6']),
    StationInfo(id: 'RFM', name: 'Rhythm Station　エフエム山形', areaIds: ['JP6']),
    StationInfo(id: 'RFC', name: 'RFCラジオ福島', areaIds: ['JP7']),
    StationInfo(id: 'FMF', name: 'ふくしまFM', areaIds: ['JP7']),
    StationInfo(id: 'JOIK', name: 'NHK AM（札幌）', areaIds: ['JP1']),
    StationInfo(id: 'JOHK', name: 'NHK AM（仙台）', areaIds: ['JP2', 'JP3', 'JP4', 'JP5', 'JP6', 'JP7']),
    StationInfo(id: 'TBS', name: 'TBSラジオ', areaIds: ['JP8', 'JP9', 'JP10', 'JP11', 'JP12', 'JP13', 'JP14']),
    StationInfo(id: 'QRR', name: '文化放送', areaIds: ['JP8', 'JP9', 'JP10', 'JP11', 'JP12', 'JP13', 'JP14']),
    StationInfo(id: 'LFR', name: 'ニッポン放送', areaIds: ['JP8', 'JP9', 'JP10', 'JP11', 'JP12', 'JP13', 'JP14']),
    StationInfo(id: 'INT', name: 'interfm', areaIds: ['JP8', 'JP9', 'JP10', 'JP11', 'JP12', 'JP13', 'JP14']),
    StationInfo(id: 'FMT', name: 'TOKYO FM', areaIds: ['JP8', 'JP9', 'JP10', 'JP11', 'JP12', 'JP13', 'JP14']),
    StationInfo(id: 'FMJ', name: 'J-WAVE', areaIds: ['JP8', 'JP9', 'JP10', 'JP11', 'JP12', 'JP13', 'JP14']),
    StationInfo(id: 'JORF', name: 'ラジオ日本', areaIds: ['JP8', 'JP9', 'JP10', 'JP11', 'JP12', 'JP13', 'JP14']),
    StationInfo(id: 'BAYFM78', name: 'BAYFM78', areaIds: ['JP8', 'JP9', 'JP10', 'JP11', 'JP12', 'JP13', 'JP14']),
    StationInfo(id: 'NACK5', name: 'NACK5', areaIds: ['JP8', 'JP9', 'JP10', 'JP11', 'JP12', 'JP13', 'JP14']),
    StationInfo(id: 'YFM', name: 'ＦＭヨコハマ', areaIds: ['JP8', 'JP9', 'JP10', 'JP11', 'JP12', 'JP13', 'JP14']),
    StationInfo(id: 'IBS', name: 'LuckyFM 茨城放送', areaIds: ['JP8', 'JP9', 'JP10', 'JP11', 'JP12', 'JP13', 'JP14']),
    StationInfo(id: 'CRT', name: 'CRT栃木放送', areaIds: ['JP9']),
    StationInfo(id: 'RADIOBERRY', name: 'RADIO BERRY', areaIds: ['JP9']),
    StationInfo(id: 'FMGUNMA', name: 'FM GUNMA', areaIds: ['JP10']),
    StationInfo(id: 'JOAK', name: 'NHK AM（東京）', areaIds: ['JP8', 'JP9', 'JP10', 'JP11', 'JP12', 'JP13', 'JP14', 'JP15', 'JP19', 'JP20']),
    StationInfo(id: 'BSN', name: 'ＢＳＮラジオ', areaIds: ['JP15']),
    StationInfo(id: 'FMNIIGATA', name: 'FM NIIGATA', areaIds: ['JP15']),
    StationInfo(id: 'KNB', name: 'ＫＮＢラジオ', areaIds: ['JP16']),
    StationInfo(id: 'FMTOYAMA', name: 'ＦＭとやま', areaIds: ['JP16']),
    StationInfo(id: 'MRO', name: 'MROラジオ', areaIds: ['JP17']),
    StationInfo(id: 'HELLOFIVE', name: 'エフエム石川', areaIds: ['JP17']),
    StationInfo(id: 'FBC', name: 'FBCラジオ', areaIds: ['JP18']),
    StationInfo(id: 'FMFUKUI', name: 'FM福井', areaIds: ['JP18']),
    StationInfo(id: 'YBS', name: 'YBSラジオ', areaIds: ['JP19']),
    StationInfo(id: 'FM-FUJI', name: 'FM FUJI', areaIds: ['JP19']),
    StationInfo(id: 'SBC', name: 'SBCラジオ', areaIds: ['JP20']),
    StationInfo(id: 'FMN', name: 'ＦＭ長野', areaIds: ['JP20']),
    StationInfo(id: 'JOCK', name: 'NHK AM（名古屋）', areaIds: ['JP16', 'JP17', 'JP18', 'JP21', 'JP22', 'JP23', 'JP24']),
    StationInfo(id: 'CBC', name: 'CBCラジオ', areaIds: ['JP21', 'JP23', 'JP24']),
    StationInfo(id: 'TOKAIRADIO', name: 'TOKAI RADIO', areaIds: ['JP21', 'JP23', 'JP24']),
    StationInfo(id: 'GBS', name: 'ぎふチャン', areaIds: ['JP21', 'JP23', 'JP24']),
    StationInfo(id: 'ZIP-FM', name: 'ZIP-FM', areaIds: ['JP21', 'JP23', 'JP24']),
    StationInfo(id: 'FMAICHI', name: 'FM AICHI', areaIds: ['JP21', 'JP23', 'JP24']),
    StationInfo(id: 'FMGIFU', name: 'ＦＭ ＧＩＦＵ', areaIds: ['JP21']),
    StationInfo(id: 'SBS', name: 'SBSラジオ', areaIds: ['JP22']),
    StationInfo(id: 'K-MIX', name: 'K-MIX', areaIds: ['JP22']),
    StationInfo(id: 'FMMIE', name: 'レディオキューブ ＦＭ三重', areaIds: ['JP24']),
    StationInfo(id: 'ABC', name: 'ABCラジオ', areaIds: ['JP25', 'JP26', 'JP27', 'JP28', 'JP29', 'JP30']),
    StationInfo(id: 'MBS', name: 'MBSラジオ', areaIds: ['JP25', 'JP26', 'JP27', 'JP28', 'JP29', 'JP30']),
    StationInfo(id: 'OBC', name: 'OBCラジオ大阪', areaIds: ['JP25', 'JP26', 'JP27', 'JP28', 'JP29', 'JP30']),
    StationInfo(id: 'CCL', name: 'FM COCOLO', areaIds: ['JP25', 'JP26', 'JP27', 'JP28', 'JP29', 'JP30']),
    StationInfo(id: 'FMO', name: 'FM大阪', areaIds: ['JP25', 'JP26', 'JP27', 'JP28', 'JP29', 'JP30']),
    StationInfo(id: 'CRK', name: 'ラジオ関西', areaIds: ['JP25', 'JP26', 'JP27', 'JP28', 'JP29', 'JP30']),
    StationInfo(id: 'KISSFMKOBE', name: 'Kiss FM KOBE', areaIds: ['JP25', 'JP26', 'JP27', 'JP28', 'JP29', 'JP30']),
    StationInfo(id: 'E-RADIO', name: 'e-radio FM滋賀', areaIds: ['JP25']),
    StationInfo(id: 'KBS', name: 'KBS京都ラジオ', areaIds: ['JP25', 'JP26', 'JP27', 'JP28', 'JP29', 'JP30']),
    StationInfo(id: 'ALPHA-STATION', name: 'α-STATION FM KYOTO', areaIds: ['JP25', 'JP26', 'JP27', 'JP28', 'JP29', 'JP30']),
    StationInfo(id: 'WBS', name: 'wbs和歌山放送', areaIds: ['JP27', 'JP30']),
    StationInfo(id: 'JOBK', name: 'NHK AM（大阪）', areaIds: ['JP25', 'JP26', 'JP27', 'JP28', 'JP29', 'JP30']),
    StationInfo(id: 'BSS', name: 'BSSラジオ', areaIds: ['JP31', 'JP32']),
    StationInfo(id: 'FM-SANIN', name: 'エフエム山陰', areaIds: ['JP31', 'JP32']),
    StationInfo(id: 'RSK', name: 'ＲＳＫラジオ', areaIds: ['JP33']),
    StationInfo(id: 'FM-OKAYAMA', name: 'ＦＭ岡山', areaIds: ['JP33']),
    StationInfo(id: 'RCC', name: 'RCCラジオ', areaIds: ['JP34']),
    StationInfo(id: 'HFM', name: '広島FM', areaIds: ['JP34']),
    StationInfo(id: 'KRY', name: 'ＫＲＹ山口放送', areaIds: ['JP35']),
    StationInfo(id: 'FMY', name: 'エフエム山口', areaIds: ['JP35']),
    StationInfo(id: 'JRT', name: 'ＪＲＴ四国放送', areaIds: ['JP36']),
    StationInfo(id: 'FM807', name: 'FM徳島', areaIds: ['JP36']),
    StationInfo(id: 'RNC', name: 'RNC西日本放送', areaIds: ['JP37']),
    StationInfo(id: 'FMKAGAWA', name: 'FM香川', areaIds: ['JP37']),
    StationInfo(id: 'RNB', name: 'RNB南海放送', areaIds: ['JP38']),
    StationInfo(id: 'JOEU-FM', name: 'FM愛媛', areaIds: ['JP38']),
    StationInfo(id: 'RKC', name: 'RKC高知放送', areaIds: ['JP39']),
    StationInfo(id: 'HI-SIX', name: 'エフエム高知', areaIds: ['JP39']),
    StationInfo(id: 'JOFK', name: 'NHK AM（広島）', areaIds: ['JP31', 'JP32', 'JP33', 'JP34', 'JP35']),
    StationInfo(id: 'JOZK', name: 'NHK AM（松山）', areaIds: ['JP36', 'JP37', 'JP38', 'JP39']),
    StationInfo(id: 'RKB', name: 'RKBラジオ', areaIds: ['JP40', 'JP41']),
    StationInfo(id: 'KBC', name: 'KBCラジオ', areaIds: ['JP40', 'JP41']),
    StationInfo(id: 'LOVEFM', name: 'LOVE FM', areaIds: ['JP40']),
    StationInfo(id: 'CROSSFM', name: 'CROSS FM', areaIds: ['JP40']),
    StationInfo(id: 'FMFUKUOKA', name: 'FM FUKUOKA', areaIds: ['JP40']),
    StationInfo(id: 'FMS', name: 'エフエム佐賀', areaIds: ['JP41']),
    StationInfo(id: 'NBC', name: 'NBCラジオ', areaIds: ['JP41', 'JP42']),
    StationInfo(id: 'FMNAGASAKI', name: 'FM長崎', areaIds: ['JP42']),
    StationInfo(id: 'RKK', name: 'RKKラジオ', areaIds: ['JP43']),
    StationInfo(id: 'FMK', name: 'FMKエフエム熊本', areaIds: ['JP43']),
    StationInfo(id: 'OBS', name: 'OBSラジオ', areaIds: ['JP44']),
    StationInfo(id: 'FM_OITA', name: 'エフエム大分', areaIds: ['JP44']),
    StationInfo(id: 'MRT', name: '宮崎放送', areaIds: ['JP45']),
    StationInfo(id: 'JOYFM', name: 'エフエム宮崎', areaIds: ['JP45']),
    StationInfo(id: 'MBC', name: 'ＭＢＣラジオ', areaIds: ['JP46']),
    StationInfo(id: 'MYUFM', name: 'μＦＭ', areaIds: ['JP46']),
    StationInfo(id: 'RBC', name: 'RBCiラジオ', areaIds: ['JP47']),
    StationInfo(id: 'ROK', name: 'ラジオ沖縄', areaIds: ['JP47']),
    StationInfo(id: 'FM_OKINAWA', name: 'FM沖縄', areaIds: ['JP47']),
    StationInfo(id: 'JOLK', name: 'NHK AM（福岡）', areaIds: ['JP40', 'JP41', 'JP42', 'JP43', 'JP44', 'JP45', 'JP46', 'JP47']),
    StationInfo(id: 'RN1', name: 'ラジオNIKKEI第1', areaIds: ['JP1', 'JP2', 'JP3', 'JP4', 'JP5', 'JP6', 'JP7', 'JP8', 'JP9', 'JP10', 'JP11', 'JP12', 'JP13', 'JP14', 'JP15', 'JP16', 'JP17', 'JP18', 'JP19', 'JP20', 'JP21', 'JP22', 'JP23', 'JP24', 'JP25', 'JP26', 'JP27', 'JP28', 'JP29', 'JP30', 'JP31', 'JP32', 'JP33', 'JP34', 'JP35', 'JP36', 'JP37', 'JP38', 'JP39', 'JP40', 'JP41', 'JP42', 'JP43', 'JP44', 'JP45', 'JP46', 'JP47']),
    StationInfo(id: 'RN2', name: 'ラジオNIKKEI第2', areaIds: ['JP1', 'JP2', 'JP3', 'JP4', 'JP5', 'JP6', 'JP7', 'JP8', 'JP9', 'JP10', 'JP11', 'JP12', 'JP13', 'JP14', 'JP15', 'JP16', 'JP17', 'JP18', 'JP19', 'JP20', 'JP21', 'JP22', 'JP23', 'JP24', 'JP25', 'JP26', 'JP27', 'JP28', 'JP29', 'JP30', 'JP31', 'JP32', 'JP33', 'JP34', 'JP35', 'JP36', 'JP37', 'JP38', 'JP39', 'JP40', 'JP41', 'JP42', 'JP43', 'JP44', 'JP45', 'JP46', 'JP47']),
    StationInfo(id: 'JOAK-FM', name: 'NHK FM（東京）', areaIds: ['JP1', 'JP2', 'JP3', 'JP4', 'JP5', 'JP6', 'JP7', 'JP8', 'JP9', 'JP10', 'JP11', 'JP12', 'JP13', 'JP14', 'JP15', 'JP16', 'JP17', 'JP18', 'JP19', 'JP20', 'JP21', 'JP22', 'JP23', 'JP24', 'JP25', 'JP26', 'JP27', 'JP28', 'JP29', 'JP30', 'JP31', 'JP32', 'JP33', 'JP34', 'JP35', 'JP36', 'JP37', 'JP38', 'JP39', 'JP40', 'JP41', 'JP42', 'JP43', 'JP44', 'JP45', 'JP46', 'JP47']),
  ];
}